import type { getPrismaClient } from '../../src/index.js';

type PrismaClient = ReturnType<typeof getPrismaClient>;

const categories = [
  { name: 'Inteligencia artificial', slug: 'inteligencia-artificial' },
  { name: 'Investigación', slug: 'investigacion' },
  { name: 'Publicaciones', slug: 'publicaciones' },
  { name: 'Eventos', slug: 'eventos' },
  { name: 'Convocatorias', slug: 'convocatorias' },
  { name: 'Actualidad', slug: 'actualidad' },
  { name: 'IA responsable', slug: 'ia-responsable' },
] as const;

const defaultKeywords = [
  'inteligencia artificial',
  'artificial intelligence',
  'machine learning',
  'aprendizaje automático',
  'deep learning',
  'generative ai',
  'ia generativa',
  'large language model',
  'llm',
  'computer vision',
  'visión computacional',
  'natural language processing',
  'procesamiento de lenguaje natural',
  'ai regulation',
  'regulación de inteligencia artificial',
  'responsible ai',
  'robotics',
  'robótica',
  'foundation model',
  'multimodal',
  'ai agent',
  'agente de ia',
] as const;

const defaultExcludedKeywords = [
  'descuento',
  'promoción',
  'sponsored',
  'patrocinado',
  'oferta comercial',
] as const;

const externalNewsSources = [
  {
    key: 'google-ai',
    name: 'Google AI',
    domain: 'blog.google',
    websiteUrl: 'https://blog.google/innovation-and-ai/technology/ai/',
    listingUrl: 'https://blog.google/innovation-and-ai/technology/ai/',
    feedUrl: 'https://blog.google/feed/',
    type: 'CORPORATE_BLOG' as const,
    language: 'en',
    includeUrlPatterns: ['/innovation-and-ai/', '/technology/ai/'],
    excludeUrlPatterns: ['/products/', '/shopping/'],
    checkIntervalMinutes: 180,
  },
  {
    key: 'mit-news-ai',
    name: 'MIT News — Artificial Intelligence',
    domain: 'news.mit.edu',
    websiteUrl: 'https://news.mit.edu/topic/artificial-intelligence2',
    listingUrl: 'https://news.mit.edu/topic/artificial-intelligence2',
    feedUrl: 'https://news.mit.edu/rss/topic/artificial-intelligence2',
    type: 'UNIVERSITY' as const,
    language: 'en',
    includeUrlPatterns: ['/20'],
    excludeUrlPatterns: ['/topic/', '/search'],
    checkIntervalMinutes: 360,
  },
  {
    key: 'arxiv-cs-ai',
    name: 'arXiv — Artificial Intelligence',
    domain: 'arxiv.org',
    websiteUrl: 'https://arxiv.org/list/cs.AI/recent',
    listingUrl: 'https://arxiv.org/list/cs.AI/recent',
    feedUrl: 'https://rss.arxiv.org/rss/cs.AI',
    type: 'ACADEMIC' as const,
    language: 'en',
    includeUrlPatterns: ['/abs/'],
    excludeUrlPatterns: ['/list/', '/pdf/'],
    checkIntervalMinutes: 720,
  },
  {
    key: 'microsoft-ai',
    name: 'Microsoft — AI',
    domain: 'news.microsoft.com',
    websiteUrl: 'https://news.microsoft.com/source/topics/ai/',
    listingUrl: 'https://news.microsoft.com/source/topics/ai/',
    feedUrl: null,
    type: 'CORPORATE_RESEARCH' as const,
    language: 'en',
    includeUrlPatterns: ['/source/', '/features/'],
    excludeUrlPatterns: ['/tag/', '/author/'],
    checkIntervalMinutes: 240,
  },
  {
    key: 'ibm-research',
    name: 'IBM Research',
    domain: 'research.ibm.com',
    websiteUrl: 'https://research.ibm.com/blog',
    listingUrl: 'https://research.ibm.com/blog',
    feedUrl: null,
    type: 'CORPORATE_RESEARCH' as const,
    language: 'en',
    includeUrlPatterns: ['/blog/'],
    excludeUrlPatterns: ['/people/', '/careers/'],
    checkIntervalMinutes: 360,
  },
  {
    key: 'databricks-blog',
    name: 'Databricks Blog',
    domain: 'databricks.com',
    websiteUrl: 'https://www.databricks.com/es/blog',
    listingUrl: 'https://www.databricks.com/es/blog',
    feedUrl: null,
    type: 'CORPORATE_BLOG' as const,
    language: 'es',
    includeUrlPatterns: ['/blog/'],
    excludeUrlPatterns: ['/category/', '/author/', '/events/'],
    checkIntervalMinutes: 180,
  },
  {
    key: 'agencia-andina',
    name: 'Agencia Andina',
    domain: 'andina.pe',
    websiteUrl: 'https://andina.pe/',
    listingUrl: 'https://andina.pe/',
    feedUrl: null,
    type: 'NEWS_AGENCY' as const,
    language: 'es',
    includeUrlPatterns: ['/agencia/noticia-'],
    excludeUrlPatterns: ['/fotografia/', '/galeria/'],
    checkIntervalMinutes: 120,
  },
  {
    key: 'dw',
    name: 'DW',
    domain: 'dw.com',
    websiteUrl: 'https://www.dw.com/es/',
    listingUrl: 'https://www.dw.com/es/',
    feedUrl: null,
    type: 'NEWS_MEDIA' as const,
    language: 'es',
    includeUrlPatterns: ['/es/'],
    excludeUrlPatterns: ['/multimedia/', '/programas/'],
    checkIntervalMinutes: 120,
  },
  {
    key: 'el-pais',
    name: 'EL PAÍS',
    domain: 'elpais.com',
    websiteUrl: 'https://elpais.com/tecnologia/',
    listingUrl: 'https://elpais.com/tecnologia/',
    feedUrl: null,
    type: 'NEWS_MEDIA' as const,
    language: 'es',
    includeUrlPatterns: ['/tecnologia/', '/ciencia/'],
    excludeUrlPatterns: ['/autor/', '/tag/', '/archivo/'],
    checkIntervalMinutes: 120,
  },
  {
    key: 'stanford-hai',
    name: 'Stanford HAI',
    domain: 'hai.stanford.edu',
    websiteUrl: 'https://hai.stanford.edu/news',
    listingUrl: 'https://hai.stanford.edu/news',
    feedUrl: null,
    type: 'UNIVERSITY' as const,
    language: 'en',
    includeUrlPatterns: ['/news/'],
    excludeUrlPatterns: ['/events/', '/people/'],
    checkIntervalMinutes: 360,
  },
] as const;

export async function seedInstitutionalData(prisma: PrismaClient): Promise<void> {
  for (const category of categories) {
    await prisma.category.upsert({
      where: { slug: category.slug },
      update: { name: category.name, active: true },
      create: { name: category.name, slug: category.slug },
    });
  }

  for (const source of externalNewsSources) {
    await prisma.externalNewsSource.upsert({
      where: { key: source.key },
      update: {
        name: source.name,
        domain: source.domain,
        websiteUrl: source.websiteUrl,
        listingUrl: source.listingUrl,
        feedUrl: source.feedUrl,
        type: source.type,
        status: 'ACTIVE',
        ingestionMethod: 'AUTO',
        language: source.language,
        includeKeywords: [...defaultKeywords],
        excludeKeywords: [...defaultExcludedKeywords],
        includeUrlPatterns: [...source.includeUrlPatterns],
        excludeUrlPatterns: [...source.excludeUrlPatterns],
        reviewMode: 'REQUIRED',
        minimumRelevanceScore: 30,
        maxItemsPerSync: 15,
        checkIntervalMinutes: source.checkIntervalMinutes,
        nextSyncAt: new Date(),
        deletedAt: null,
      },
      create: {
        ...source,
        status: 'ACTIVE',
        ingestionMethod: 'AUTO',
        includeKeywords: [...defaultKeywords],
        excludeKeywords: [...defaultExcludedKeywords],
        reviewMode: 'REQUIRED',
        minimumRelevanceScore: 30,
        maxItemsPerSync: 15,
        nextSyncAt: new Date(),
      },
    });
  }
}
